### ISSUE TITLE
FinancialResourceStatusCodesEnum keys must be un UPPERCASES

### ISSUE THREAD

**Issue by robertoAraneda** [robertoAraneda/fhir-types#76]
export declare enum FinancialResourceStatusCodesEnum {
    active = "active",
    cancelled = "cancelled",
    draft = "draft",
    entered_in_error = "entered-in-error"
}

**Comment by ClaudiaAlarconLazo** [comment]
it was solved in issue 72

**Comment by robertoAraneda** [comment]
closed
